config/routes.rb
ShopifyOauth2Example::Application.routes.draw do
  root to: "home#index"
  
  match "/auth/:provider/callback" => "shopify/sessions#create", :as => :authenticate
  
  namespace :shopify do
    resource :session, :only => [:new, :create, :destroy]
  end
end

app/models/shop.rb
class Shop < ActiveRecord::Base
  attr_accessible :provider, :domain, :token
  
  validates_uniqueness_of :token, :on => :create
  
  validates_presence_of :provider, :token
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  helper_method :current_shop, :shopify_session

  private

  def current_shop
    @current_shop ||= Shop.find(session[:shop_id]) if session[:shop_id].present?
  end
  
  def shopify_session
    unless current_shop.nil?
      api_key = Rails.configuration.shopify_api_key
      token   = current_shop.token
      domain  = current_shop.domain
      
      ShopifyAPI::Base.site = "https://#{api_key}:#{token}@#{domain}/admin"
    end
    
    yield if block_given?
    
    ensure ShopifyAPI::Base.site = nil
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if current_shop.nil?
      render 'welcome'
    else
      shopify_session { @products = ShopifyAPI::Product.find(:all, params: {limit: 5}) }
    end
  end
  
  def welcome
  end
end

app/controllers/shopify/sessions_controller.rb
class Shopify::SessionsController < ApplicationController
  def create
    # get the omniauth request
    auth = request.env["omniauth.auth"]
    
    # find or create the shop
    shop = Shop.find_or_create_by_provider_and_token(
      auth["provider"],
      auth["credentials"].token
    )
    
    # ensure the shop's domain is stored in the local database
    shop.update_attributes(:domain => params[:shop]) if shop.domain.empty?
    
    # store the shop's identifier in the session
    session[:shop_id] = shop.to_param
    
    # redirect to the root path
    redirect_to root_path, :notice => "Signed in."
  end

  def destroy
    # reset the session - safer than just deleting
    # :shop_id, as it also prevents session hijacking
    reset_session
    
    # redirect to the root path
    redirect_to root_path, :notice => "Signed out."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/shopify/sessions_helper.rb
module Shopify::SessionsHelper
end

app/views/home/index.html.slim
h1 Home

p Here are some products:

ul
  - @products.each do |product|
    li = product.title

app/views/home/welcome.html.slim
h1 Welcome
p
  | Please #{link_to "sign in", new_shopify_session_path} to continue.

app/views/layouts/application.html.slim
doctype html
html
  head
    title Shopify OAuth2 Example
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  body
    ul
      - if current_shop.nil?
        li = link_to "Sign in", new_shopify_session_path
      - else
        li = current_shop.domain
        li = link_to "Sign out", shopify_session_path,
          :confirm => "Are you sure?",
          :method  => :delete
    = yield